#Set up your PostgreSQL database information
database:
  host:
  port:
  name:
  username:
  password:
  ranks:
    not_exists: 'NOT_EXISTS'
    10: 'PLAYER'
    20: 'VIP'
    30: 'SVIP'
    40: 'SPONSOR'
    50: 'YOUTUBER'
    60: 'TWITCHER'
    70: 'HELPER'
    80: 'MODERATOR'
    90: 'ADMIN'
    100: 'HEADADMIN'
    110: 'OWNER'

language: en

sound:
  resource: 'https://papermc.io/javadocs/paper/1.12/org/bukkit/Sound.html'
  gban:
  ban:
  gkick:
  kick:
  mute:
  mutechat:

lobby_server_name: 'lobby'

#Name your database table to specific servers
#default_table is set by default
server:
  blacklist: 'blacklist'